/*
 * This source file was generated by the Gradle 'init' task
 */
package bt7s7k7.treeburst;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import bt7s7k7.treeburst.support.Primitive;

class AppTest {
	@Test
	void primitiveValues() {
		var number = new Primitive.Number(58);
		assertEquals(number.value, 58);
	}
}
